### ISSUE TITLE
Anthology routes and views

### ISSUE THREAD

**Issue by jamiefolsom** [performant-software/Annotation-Studio#161]
Necessary features
- Anthology show view is a list of documents, with a URL like `/anthologies/:friendly_id/`
- Anthology list view is a list of anthologies, with names and descriptions, with a way to assign an anthology to a group of students
- Clicking on a document from the anthology show view accesses an existing document, at URL like `/anthologies/:friendly_id/documents/:friendly_id`

**Comment by SteveMarvin** [comment]
I can add another user's shared document to multiple anthologies, and they appear in each with different URLs just fine.

But if I add one of **my own** docs to an anthology, and then add it to another anthology, it is removed from the first anthology and only appears in the second. Is this expected behavior?

**Comment by jamiefolsom** [comment]
Complete.

**Comment by jamiefolsom** [comment]
@SteveMarvin, when next you're in, can you confirm that you can add your own documents to many anthologies (requires you to log in as an admin). Thanks!

**Comment by SteveMarvin** [comment]
Can do!
