### ISSUE TITLE
As a student, I can’t access documents from anthologies

### ISSUE THREAD

**Issue by jamiefolsom** [performant-software/Annotation-Studio#260]
- Sign in as a student
- Go to an anthology
- Click a document
- You see "You are not authorized to access this page."

**Comment by SteveMarvin** [comment]
Entire test plan smooth as silk until the last step. First document I added to the anthology and hen clicked on, I was told I was not authorized to access the resource and got these errors in the console:
![image](https://user-images.githubusercontent.com/18423533/83531451-ff297200-a4ba-11ea-959c-1d6696d59547.png)
 

Thinking that might be because I added a document I had not created/uploaded myself, I uploaded a document and tried to access that. Got an endless spinner and this error: 
![image](https://user-images.githubusercontent.com/18423533/83531344-dc975900-a4ba-11ea-832a-3498caf544ed.png)

**Comment by jamiefolsom** [comment]
Done.
