### ISSUE TITLE
Screencast: Annotation Studio Documents

### ISSUE THREAD

**Issue by jamiefolsom** [performant-software/Annotation-Studio#66]
This screencast covers the basics of document 
- Creation
- Phases

See: https://drive.google.com/open?id=0B4r_9zFhjag8d0EwaE5jR2NuYjA

**Comment by SteveMarvin** [comment]
Generally good...same issues as elsewhere with _describing_ what things _would_ look like rather than demonstrating those features _in situ_. There's a bit of "well, actually, why don't we do this instead.." going on, but that's not really detracting, given the format. Ending is a little abrupt, but generally :+1:.
