### ISSUE TITLE
Screencast: Edition and Team Tags

### ISSUE THREAD

**Issue by jamiefolsom** [performant-software/Annotation-Studio#91]
This screencast will show you how to:
- Add "edition" and "team" tags to your account
- Add edition tags to documents to share them with other editors

See: 

https://drive.google.com/open?id=0B4r_9zFhjag8Ul9YdVlSQUdQLVU

**Comment by jamiefolsom** [comment]
Hi @SteveMarvin -- would be glad for your feedback on this screencast. Thanks!

**Comment by SteveMarvin** [comment]
So this seems generally fine...there are some long pauses and non-presentation language (The join-me-on-a-personal-journey feeling of "I am now going to go up here and click on this link here..." is probably better stated in the vocative: "Click on the My Profile link in the upper right", etc.). These videos don't seem too formal, so as long as they are meant for insiders, not general public, that kind of thing is fine. 

The one thing I do question is deciding not actually to create a document at the end , and afterwards trying to describe what they would be seeing if you had done so. that's potentially confusing, and unnecessarily so. Just create the document and cut that part out of the video, so the edit jumps from starting to fill it out to the completed form, then pick up with "Now that all of the fields are filled out, I create the document and we can now see it appear in the correct locations on the dashboard, etc.". You can always point them to the video that describes the document creation process in detail. 

I'm not going to put this in Reject, since it is a matter of style to a degree, but it is worth thinking about.

**Comment by jamiefolsom** [comment]
Points very well taken. I will work on improving them as you suggest. Thanks @SteveMarvin !
